DROP TABLE IF EXISTS ITEM_INFO;
DROP TABLE IF EXISTS USER_INFO;
DROP TABLE IF EXISTS CART_INFO;

CREATE TABLE ITEM_INFO
(
    ID        BIGINT       NOT NULL AUTO_INCREMENT,
    NAME      VARCHAR(10)  NOT NULL,
    PRICE     INT          NOT NULL,
    IMAGE_URL VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE USER_INFO
(
    ID        BIGINT       NOT NULL AUTO_INCREMENT,
    email VARCHAR(15)  NOT NULL,
    PASSWORD      VARCHAR(15)  NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE CART_INFO
(
    ID        BIGINT       NOT NULL AUTO_INCREMENT,
    NAME      VARCHAR(10)  NOT NULL,
    PRICE     INT          NOT NULL,
    IMAGE_URL VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(15)  NOT NULL,
    PRIMARY KEY (id)
)