DROP TABLE IF EXISTS ITEM_INFO;
DROP TABLE IF EXISTS USER_INFO;

CREATE TABLE ITEM_INFO
(
    ID        BIGINT       NOT NULL AUTO_INCREMENT,
    NAME      VARCHAR(10)  NOT NULL,
    PRICE     INT          NOT NULL,
    IMAGE_URL VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE USER_INFO
(
    ID        BIGINT       NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(15)  NOT NULL,
    PASSWORD      VARCHAR(15)  NOT NULL,
    PRIMARY KEY (id)
);

insert into USER_INFO (ID,USER_ID, PASSWORD)
values (1,'user1','password1');

insert into USER_INFO (ID,USER_ID, PASSWORD)
values (2,'user2','password2');